# Change 'comments' to true for Disqus comments
disqus:
  comments: false

# If you are not using Google Analytics, please change 'google-ID' to an empty string

menu:
- {name: '个人简介', path: 'menu', url: 'about.html'}
- {name: '文章', path: 'menu', url: 'writing.html'}
- {name: '联系我', path: 'menu', url: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github', link: 'https://www.github.com/'}
- {icon: 'twitter', link: 'https://twitter.com/'}
- {icon: 'linkedin', link: 'http://www.linkedin.com/'}

# Customize site text
pagination:
  next_page: '下一页'
  previous_page: '上一页'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy:'

post_date_prefix: 'Written on'
